/* AS3
	Copyright 2008
*/
package com.neopets.util.collision
{
	import com.neopets.util.collision.objects.CollisionSensor;
	
	/**
	 *	The class is a simple wrapper for information generated by a collision event
	 * 
	 *	@langversion ActionScript 3.0
	 *	@playerversion Flash 9.0
	 *	@Pattern Singelton
	 * 
	 *	@author David Cary
	 *	@since  8.24.2009
	 */
	public class CollisionData
	{
		
		//--------------------------------------
		// CLASS CONSTANTS
		//--------------------------------------
		
		//--------------------------------------
		//  PRIVATE VARIABLES
		//--------------------------------------
		protected var _mover:CollisionSensor;
		protected var _other:CollisionSensor;
		
		//--------------------------------------
		//  CONSTRUCTOR
		//--------------------------------------
		
		/**
		 *	@Constructor
		 */
		public function CollisionData(p1:CollisionSensor,p2:CollisionSensor):void{
			_mover = p1;
			_other = p2;
		}
		
		//--------------------------------------
		//  GETTER/SETTERS
		//--------------------------------------
		
		/**
		 * @This function returns the first proxy in the collision
		 */
		 
		public function get mover():CollisionSensor { return _mover; }
		
		/**
		 * @This function returns the second proxy in the collision
		 */
		 
		public function get other():CollisionSensor { return _other; }
		
		//--------------------------------------
		//  PUBLIC METHODS
		//--------------------------------------
		
		/**
		 * @This function returns a string representation of this object.
		 */
		 
		public function toString():String{
			return _mover + " collided with " + _other;
		}
		
		//--------------------------------------
		//  EVENT HANDLERS
		//--------------------------------------
		
		//--------------------------------------
		//  PRIVATE & PROTECTED INSTANCE METHODS
		//--------------------------------------
		
	}
	
}
